CREATE DATABASE  IF NOT EXISTS `conferences`;
USE `conferences`;

DROP TABLE IF EXISTS `T_DAY`;
CREATE TABLE `T_DAY` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `start` int(1) DEFAULT NULL,
  `end` int(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
);


LOCK TABLES `T_DAY` WRITE;
ALTER TABLE `T_DAY` DISABLE KEYS;
INSERT INTO `T_DAY` VALUES (15,6,14);
ALTER TABLE `T_DAY` ENABLE KEYS;
UNLOCK TABLES;